name: multibidings_example
description: Example demonstrating injectable_multibindings usage.
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  injectable_multibindings:
    path: ../injectable_multibindings
  injectable: ^2.3.0
  get_it: ^7.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  injectable_multibindings_generator:
    path: ../injectable_multibindings_generator
  injectable_generator: ^2.6.0
