builders:
  multibinding:
    import: "package:injectable_multibindings_generator/injectable_multibindings_generator_builder.dart"
    builder_factories: ["multibindingBuilder"]
    build_extensions: {".dart": [".multibindings.dart"]}
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      injectable_multibindings_generator:multibinding:
        enabled: true
        generate_for:
          - lib/**/*.dart
