targets:
  $default:
    builders:
      injectable_multibindings_generator:multibinding:
        enabled: true
        generate_for:
          - lib/**/*.dart
        options:
          build_extensions:
            ".dart": [".multibindings.dart"]
      

