name: injectable_multibindings
description: Multibinding support for injectable dependency injection. Automatically collect multiple implementations of the same interface into lists.
version: 1.0.0
homepage: https://github.com/yourusername/injectable_multibindings
repository: https://github.com/yourusername/injectable_multibindings

environment:
  sdk: ^3.7.2

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
